apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-test-app
  namespace: devops-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: devops-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-test-app
                port:
                  number: 80
