apiVersion: v2
name: devops-test-app
description: A Helm chart for FastAPI DevOps Test Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - python
  - api
maintainers:
  - name: archicisco
